version: "3.3"

services:
  app:
    restart: always
    build: ./app
    ports:
      - 4200:3000
    depends_on:
      - server

  server:
    restart: always
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pokemon
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5000:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
