services:
  app:
    restart: always
    build: ./app
    image: app-test-express-react_app
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    restart: always
    build: ./server
    image: app-test-express-react_server
    ports:
      - 4024:4024
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=pokemon
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5000:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
